version: '2'
services:
  dashboard:
    image: taichunmin/git-it-course-docker:dashboard
    environment:
      - DEBUG=socket.io:*,dashboard:*
    networks:
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webapp:/var/www/html
      - ./dashboard/motd:/etc/motd:ro
    ports:
      - "80:80"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    networks:
      - backend
    restart: always
  client:
    image: taichunmin/git-it-course-docker:client
    networks:
      - frontend
    depends_on:
      - dashboard
    volumes:
      - ./client/motd:/etc/motd:ro
    ports:
      - "22"
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
