name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Dockerfile
        run: docker-compose -f docker-build.yml build

      - name: Push Image to Dockerhub
        run: docker-compose -f docker-build.yml push
